### ISSUE TITLE
Export partonomy to JSON (or YML)

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hubmap-ontology#7]
To simplify browser usage, in addition to outputting standard RDF/OWL files, export a simplified JSON (or YML) format for displaying the partonomy. The structure should include for each node: the Uberon id, the full IRI, preferred label, 'has exact synonym' labels, and its children. The details are up for discussion.

It would look something like this in YAML:
```yml
- id: UBERON_123
  iri: http://uberonurlblah.com/123
  label: Kidney
  altLabels:
    - renal
    - another alternative
    - etc
  
  children:
    - id: UBERON_345
      iri: http://uberonurlblah.com/345
      label: Thing in Kidney
      altLabels:
        - renal thing
        - another alternative thing
        - etc thing
```

Design the export function to be extended later as we may add more metadata later on.

**Comment by SamuelFriedman** [comment]
Want parent class listed, not children classes listed. (AKA arrows point up the tree).

**Comment by SamuelFriedman** [comment]
As part of creating the updated reifications in #3, we now have a JSON structure.

**Comment by SamuelFriedman** [comment]
When creating the partonomy, it breaks the method we use for cleaning up unnecessary terms in Protege because there are now too many extra.

**Comment by SamuelFriedman** [comment]
In Protege, any terms that do not have a label are to be deleted. Any terms with labels remain.

**Comment by SamuelFriedman** [comment]
JSON-LD will NOT work. Replicate this structure:
```yml
- id: UBERON_123
  iri: http://uberonurlblah.com/123
  parent: UBERON_345
  label: Kidney
  altLabels:
    - renal
    - another alternative
    - etc  
```
